### ISSUE TITLE
Fix a bug where duplicate SDK compliance issues are created

### ISSUE THREAD

**Issue by IEvangelist** [dotnet/versionsweeper#36]
See: https://github.com/dotnet/dotnet-api-docs/issues?q=is%3Aopen+is%3Aissue+label%3Adotnet-target-version

Note, the first https://github.com/dotnet/dotnet-api-docs/issues/6583 should be created - but it should not be duplicated

**Comment by gewarren** [comment]
If we run this every month and no changes are made to the projects, will duplicate issues be created?

**Comment by IEvangelist** [comment]
> If we run this every month and no changes are made to the projects, will duplicate issues be created?

No, duplicates are avoided in 99% of the cases as there is a preemptive check.
