### ISSUE TITLE
Support for scanning Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [dotnet/versionsweeper#73]
Dockerfiles are another file type that would be good to support. They contain references to image tags that specify the .NET version number. These tags are a good example of where a patch version can be specified. Patch versions become EOL even more frequently since they get replaced each month by a newer version.

You can find all official .NET container tags at:
* .NET [Core]: https://hub.docker.com/_/microsoft-dotnet
* .NET Framework: https://hub.docker.com/_/microsoft-dotnet-framework

Here are just a few examples of tags:

.NET version:

```Dockerfile
FROM mcr.microsoft.com/dotnet:aspnet:6.0
```

.NET patch version:

```Dockerfile
FROM mcr.microsoft.com/dotnet:aspnet:6.0.0
```

Simple major/minor .NET version with OS:
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine3.16
```

.NET Framework version:
```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8
```

.NET Framework version with month timestamp:
```Dockerfile
FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-20221011-windowsservercore-ltsc2022
```

Should also consider looking for tags in `COPY` instructions in addition to `FROM`:

```Dockerfile
COPY --from=mcr.microsoft.com/dotnet/sdk:6.0 /usr/share/dotnet/shared /usr/share/dotnet/shared
```

**Comment by IEvangelist** [comment]
Hi @mthalman - thank you for the idea, you're absolutely right. This is something that we should certain work to support, and it shouldn't be too hard. I'll try to work on adding that!
